// <auto-generated />
using System;
using HavaMeydanlariWebApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HavaMeydanlariWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231019191919_crt")]
    partial class crt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HavaMeydanlariWebApi.Model.Firmalar", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirmaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FirmaBütcesi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirmaMerkezi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FirmaId");

                    b.ToTable("Firmalars");
                });

            modelBuilder.Entity("HavaMeydanlariWebApi.Model.HavaLimanlar", b =>
                {
                    b.Property<int>("HavaLimaniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Maliyeti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PistSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Yerleskesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YolcuKapasitesi")
                        .HasColumnType("int");

                    b.HasKey("HavaLimaniId");

                    b.ToTable("HavaLimanlars");
                });

            modelBuilder.Entity("HavaMeydanlariWebApi.Model.Personeller", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CalismaTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("HavaLimaniId")
                        .HasColumnType("int");

                    b.Property<string>("PersonelAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UcakId")
                        .HasColumnType("int");

                    b.Property<bool>("Vardiya")
                        .HasColumnType("bit");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("PersonelId");

                    b.HasIndex("HavaLimaniId");

                    b.HasIndex("UcakId");

                    b.ToTable("Personellers");
                });

            modelBuilder.Entity("HavaMeydanlariWebApi.Model.Ucaklar", b =>
                {
                    b.Property<int>("UcakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BiletFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FirmaId")
                        .HasColumnType("int");

                    b.Property<int>("UcakGenislik")
                        .HasColumnType("int");

                    b.Property<string>("UcakRengi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UcakTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YolcuKapasitesi")
                        .HasColumnType("int");

                    b.HasKey("UcakId");

                    b.HasIndex("FirmaId");

                    b.ToTable("Ucaklars");
                });

            modelBuilder.Entity("HavaMeydanlariWebApi.Model.Personeller", b =>
                {
                    b.HasOne("HavaMeydanlariWebApi.Model.HavaLimanlar", "HavaLimanlar")
                        .WithMany()
                        .HasForeignKey("HavaLimaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HavaMeydanlariWebApi.Model.Ucaklar", "Ucaklar")
                        .WithMany()
                        .HasForeignKey("UcakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HavaLimanlar");

                    b.Navigation("Ucaklar");
                });

            modelBuilder.Entity("HavaMeydanlariWebApi.Model.Ucaklar", b =>
                {
                    b.HasOne("HavaMeydanlariWebApi.Model.Firmalar", "Firmalar")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firmalar");
                });
#pragma warning restore 612, 618
        }
    }
}
